apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: mualem/kub-data:2
          env:
            - name: STORY_FOLDER
              #value: "story"  --- IGNORE ---
              valueFrom:
                configMapKeyRef:
                  name: data-store-env
                  key: folder
          volumeMounts:
            - name: story-volume
              mountPath: /app/story
          ports:
            - containerPort: 3000
      volumes:
      - name: story-volume
        persistentVolumeClaim:
          claimName: story-pvc